import type { LegalContent } from "../types";

export const privacy: LegalContent = {
  heading: "Privacy Policy",
  sections: [
    {
      heading: "Preamble",
      body: [
        'With the following privacy policy, we would like to inform you about the types of your personal data (hereinafter also referred to as "data") that we process, for what purposes, and to what extent. This privacy policy applies to all processing of personal data carried out by us, both in the context of providing our services and, in particular, on our websites, in mobile applications, and within external online presences, such as our social media profiles (hereinafter collectively referred to as "online offer").',
        "The terms used are not gender-specific.",
        "Last updated: 23 July 2026",
      ],
    },
    {
      heading: "Table of Contents",
      body: [
        "- Preamble",
        "- Data Controller",
        "- Overview of Processing Activities",
        "- Relevant Legal Bases",
        "- Security Measures",
        "- Disclosure of Personal Data",
        "- International Data Transfers",
        "- General Information on Data Storage and Deletion",
        "- Rights of Data Subjects",
        "- Business Services",
        "- Provision of the Online Offer and Web Hosting",
        "- Contact and Inquiry Management",
        "- Data Protection Information for Whistleblowers",
        "- Amendment and Update",
        "- Definitions",
      ],
    },
    {
      heading: "Data Controller",
      body: [
        "Simeon Brus Coaching",
        "Bachweg 6",
        "82327 Traubing",
        "Authorized representative: Simeon Brus",
        "Email address: simeon-brus-info@web.de",
        "Legal notice: https://simeon-brus-coach.de/impressum",
      ],
    },
    {
      heading: "Overview of Processing Activities",
      body: [
        "The following overview summarizes the types of data processed and the purposes of their processing, and refers to the data subjects concerned.",
        "Types of data processed:",
        "- Inventory data.",
        "- Employee data.",
        "- Payment data.",
        "- Contact data.",
        "- Content data.",
        "- Contract data.",
        "- Usage data.",
        "- Meta, communication and procedural data.",
        "- Log data.",
        "Categories of data subjects:",
        "- Service recipients and clients.",
        "- Employees.",
        "- Prospective customers.",
        "- Communication partners.",
        "- Users.",
        "- Business and contractual partners.",
        "- Trainees and course participants.",
        "- Third parties.",
        "- Whistleblowers.",
        "Purposes of processing:",
        "- Provision of contractual services and fulfillment of contractual obligations.",
        "- Communication.",
        "- Security measures.",
        "- Office and organizational procedures.",
        "- Organizational and administrative procedures.",
        "- Feedback.",
        "- Provision of our online offer and user-friendliness.",
        "- Information technology infrastructure.",
        "- Whistleblower protection.",
        "- Business processes and business management procedures.",
      ],
    },
    {
      heading: "Relevant Legal Bases",
      body: [
        "Relevant legal bases under the GDPR: Below you will find an overview of the legal bases of the GDPR on which we process personal data. Please note that, in addition to the provisions of the GDPR, national data protection requirements may apply in your or our country of residence or registered office. Furthermore, should more specific legal bases apply in individual cases, we will inform you of these in this privacy policy.",
        "- Consent (Art. 6(1) sentence 1(a) GDPR) - The data subject has given consent to the processing of their personal data for one or more specific purposes.",
        "- Performance of a contract and pre-contractual inquiries (Art. 6(1) sentence 1(b) GDPR) - Processing is necessary for the performance of a contract to which the data subject is party, or in order to take steps at the request of the data subject prior to entering into a contract.",
        "- Legal obligation (Art. 6(1) sentence 1(c) GDPR) - Processing is necessary for compliance with a legal obligation to which the controller is subject.",
        "- Legitimate interests (Art. 6(1) sentence 1(f) GDPR) - Processing is necessary to safeguard the legitimate interests of the controller or a third party, provided the interests, fundamental rights, and fundamental freedoms of the data subject requiring the protection of personal data do not override those interests.",
        "National data protection provisions in Germany: In addition to the data protection provisions of the GDPR, national data protection provisions apply in Germany. These include, in particular, the Act to Protect Against the Misuse of Personal Data in Data Processing (Federal Data Protection Act - BDSG). The BDSG contains, in particular, special provisions on the right to information, the right to deletion, the right to object, the processing of special categories of personal data, processing for other purposes, and automated decision-making in individual cases, including profiling. Furthermore, the data protection laws of the individual German federal states may apply.",
        'Note on the applicability of the GDPR and the Swiss FADP: These privacy notices serve to provide information both under the Swiss Federal Act on Data Protection (FADP) and under the General Data Protection Regulation (GDPR). For this reason, we ask you to note that, due to its broader territorial application and greater comprehensibility, we use the terminology of the GDPR. In particular, instead of the terms used in the Swiss FADP such as "processing" of "personal data", "overriding interest", and "particularly sensitive personal data", we use the terms used in the GDPR, namely "processing" of "personal data" as well as "legitimate interest" and "special categories of data". However, the legal meaning of these terms continues to be determined by the Swiss FADP insofar as it applies.',
      ],
    },
    {
      heading: "Security Measures",
      body: [
        "In accordance with statutory requirements, and taking into account the state of the art, the cost of implementation, and the nature, scope, context, and purposes of processing, as well as the varying likelihood and severity of the risk to the rights and freedoms of natural persons, we take appropriate technical and organizational measures to ensure a level of security appropriate to the risk.",
        "These measures include, in particular, safeguarding the confidentiality, integrity, and availability of data by controlling physical and electronic access to the data, as well as access, entry, disclosure, availability, and its segregation. We have also established procedures that ensure the exercise of data subject rights, the deletion of data, and responses to data risks. Furthermore, we take the protection of personal data into account as early as the development or selection of hardware, software, and procedures, in accordance with the principle of data protection through technology design and privacy-friendly default settings.",
        'Shortening of the IP address: To the extent that IP addresses are processed by us or by the service providers and technologies we use, and processing of the full IP address is not required, the IP address is shortened (also referred to as "IP masking"). In this process, the last two digits, or the last part of the IP address after a dot, are removed or replaced with placeholders. Shortening the IP address is intended to prevent, or substantially impede, the identification of a person based on their IP address.',
        "Securing online connections through TLS/SSL encryption technology (HTTPS): To protect the data of users transmitted via our online services from unauthorized access, we rely on TLS/SSL encryption technology. Secure Sockets Layer (SSL) and Transport Layer Security (TLS) are the cornerstones of secure data transmission on the internet. These technologies encrypt the information transmitted between the website or app and the user's browser (or between two servers), thereby protecting the data from unauthorized access. TLS, as the more advanced and more secure version of SSL, ensures that all data transmissions meet the highest security standards. When a website is secured by an SSL/TLS certificate, this is signaled by the display of HTTPS in the URL. This serves as an indicator to users that their data is being transmitted securely and encrypted.",
      ],
    },
    {
      heading: "Disclosure of Personal Data",
      body: [
        "In the course of our processing of personal data, it may occur that such data is transmitted to, or disclosed to, other bodies, companies, legally independent organizational units, or persons. Recipients of this data may include, for example, service providers commissioned with IT tasks, or providers of services and content embedded in a website. In such cases, we comply with statutory requirements and, in particular, enter into appropriate contracts or agreements that serve to protect your data with the recipients of your data.",
        "Data transfer within the organization: We may transmit personal data to other departments or units within our organization, or grant them access to it. Where such disclosure occurs for administrative purposes, it is based on our legitimate business and commercial interests, or takes place where it is necessary to fulfill our contractual obligations, or where the data subject's consent or a statutory permission exists.",
      ],
    },
    {
      heading: "International Data Transfers",
      body: [
        "Data processing in third countries: If we transfer data to a third country (i.e. outside the European Union (EU) or the European Economic Area (EEA)), or if this occurs in connection with the use of third-party services or the disclosure or transmission of data to other persons, bodies, or companies (which is apparent from the postal address of the respective provider, or where this privacy policy expressly refers to data transfers to third countries), this always takes place in accordance with statutory requirements.",
        "For data transfers to the USA, we primarily rely on the Data Privacy Framework (DPF), which was recognized as a secure legal framework by an adequacy decision of the EU Commission dated 10 July 2023. In addition, we have entered into Standard Contractual Clauses with the respective providers, which comply with the EU Commission's requirements and establish contractual obligations to protect your data.",
        "This dual safeguard ensures comprehensive protection of your data: the DPF forms the primary layer of protection, while the Standard Contractual Clauses serve as an additional safeguard. Should changes occur within the framework of the DPF, the Standard Contractual Clauses take effect as a reliable fallback option. This ensures that your data remains adequately protected at all times, even in the event of any political or legal changes.",
        "For individual service providers, we inform you whether they are certified under the DPF and whether Standard Contractual Clauses are in place. Further information on the DPF and a list of certified companies can be found on the website of the US Department of Commerce at https://www.dataprivacyframework.gov/ (in English).",
        "For data transfers to other third countries, corresponding safeguards apply, in particular Standard Contractual Clauses, explicit consent, or transmissions required by law. Information on third-country transfers and applicable adequacy decisions can be found in the information provided by the EU Commission at: https://commission.europa.eu/law/law-topic/data-protection/international-dimension-data-protection_en.",
      ],
    },
    {
      heading: "General Information on Data Storage and Deletion",
      body: [
        "We delete personal data that we process in accordance with statutory provisions as soon as the underlying consents are revoked or no further legal basis for the processing exists. This applies to cases in which the original purpose of processing no longer applies or the data is no longer needed. Exceptions to this rule apply where statutory obligations or particular interests require the data to be retained or archived for longer.",
        "In particular, data that must be retained for commercial or tax law reasons, or whose storage is necessary for the pursuit of legal claims or for the protection of the rights of other natural or legal persons, must be archived accordingly.",
        "Our privacy notices contain additional information on the retention and deletion of data that applies specifically to particular processing activities.",
        "Where multiple retention periods or deletion deadlines apply to a given piece of data, the longest period is always decisive. Data that is no longer retained for its originally intended purpose, but instead due to statutory requirements or other reasons, is processed by us exclusively for the reasons that justify its retention.",
        "Retention and deletion of data: The following general retention periods apply for retention and archiving under German law:",
        "- 10 years - retention period for books and records, annual financial statements, inventories, management reports, opening balance sheets, and the working instructions and other organizational documents required to understand them (§ 147 para. 1 no. 1 in conjunction with para. 3 AO [German Fiscal Code], § 14b para. 1 UStG [German VAT Act], § 257 para. 1 no. 1 in conjunction with para. 4 HGB [German Commercial Code]).",
        "- 8 years - accounting documents, such as invoices and cost receipts (§ 147 para. 1 no. 4 and 4a in conjunction with para. 3 sentence 1 AO, and § 257 para. 1 no. 4 in conjunction with para. 4 HGB).",
        "- 6 years - other business documents: received commercial or business letters, copies of commercial or business letters sent, and other documents relevant for tax purposes, e.g. hourly wage slips, cost accounting sheets, calculation documents, price labels, as well as payroll documents insofar as they are not already accounting documents, and cash register tapes (§ 147 para. 1 no. 2, 3, 5 in conjunction with para. 3 AO, § 257 para. 1 no. 2 and 3 in conjunction with para. 4 HGB).",
        "- 3 years - data required to take into account potential warranty and damages claims or similar contractual claims and rights, and to process related inquiries, based on past business experience and common industry practice, is stored for the duration of the standard statutory limitation period of three years (§§ 195, 199 BGB [German Civil Code]).",
        "Commencement of periods at year-end: If a period does not expressly begin on a specific date and is at least one year long, it automatically begins at the end of the calendar year in which the triggering event occurred. In the case of ongoing contractual relationships in the course of which data is stored, the triggering event is the point at which the termination or other ending of the legal relationship takes effect.",
      ],
    },
    {
      heading: "Rights of Data Subjects",
      body: [
        "Rights of data subjects under the GDPR: As a data subject, you have various rights under the GDPR, which arise in particular from Art. 15 to 21 GDPR:",
        "- Right to object: You have the right, on grounds relating to your particular situation, to object at any time to the processing of personal data concerning you which is based on Art. 6(1)(e) or (f) GDPR; this also applies to profiling based on these provisions. Where personal data concerning you is processed for the purposes of direct marketing, you have the right to object at any time to the processing of personal data concerning you for the purpose of such marketing; this also applies to profiling to the extent that it is related to such direct marketing.",
        "- Right to withdraw consent: You have the right to withdraw any consent you have given at any time.",
        "- Right of access: You have the right to request confirmation as to whether data concerning you is being processed, and to request information about this data as well as further information and a copy of the data in accordance with statutory requirements.",
        "- Right to rectification: You have the right, in accordance with statutory requirements, to request the completion of data concerning you or the correction of inaccurate data concerning you.",
        "- Right to erasure and restriction of processing: You have the right, in accordance with statutory requirements, to demand that data concerning you be deleted without delay, or, alternatively, to demand that the processing of the data be restricted in accordance with statutory requirements.",
        "- Right to data portability: You have the right to receive data concerning you that you have provided to us, in accordance with statutory requirements, in a structured, common, and machine-readable format, or to request that it be transmitted to another controller.",
        "- Right to lodge a complaint with a supervisory authority: Without prejudice to any other administrative or judicial remedy, you have the right to lodge a complaint with a supervisory authority, in particular in the Member State of your habitual residence, place of work, or place of the alleged infringement, if you consider that the processing of personal data concerning you infringes the GDPR.",
      ],
    },
    {
      heading: "Business Services",
      body: [
        "The processing serves in particular to fulfill our principal and ancillary contractual obligations. This includes the provision of the agreed services, any update and information obligations, the handling of warranty claims and other performance disruptions, the processing of withdrawals, terminations of ongoing contractual relationships, unwinding of contracts, refunds, and the handling of other contract-related declarations and inquiries. This covers both one-off contracts and ongoing contractual relationships.",
        "We process, in particular, master data such as name, address and, where applicable, company name; contact data such as email address and telephone number; contract and service data such as the subject matter of the contract, contract duration, order or reference number; usage and service data; payment and billing data; as well as communication content and histories. Where necessary, we also process data disclosed or transmitted to us in the course of carrying out an order.",
        "In addition, we process the data to safeguard our rights and to comply with statutory obligations. This includes, in particular, retention obligations under commercial and tax law, documentation obligations, and, where applicable, verification and accountability obligations. Processing is also carried out on the basis of our legitimate interests in proper business management, internal administration, risk control, and IT security, as well as in protecting our business operations and our contractual partners against misuse, endangerment of data, trade secrets, and other legal interests. This may also include the involvement of external service providers such as IT and telecommunications providers, transport and logistics companies, payment service providers, banks, tax and legal advisors, or other agents, insofar as this is necessary for the performance of the contract or to fulfill statutory obligations.",
        "Personal data is disclosed to third parties only to the extent necessary for the performance of the contract, the carrying out of pre-contractual measures, the safeguarding of legitimate interests, or the fulfillment of statutory obligations. We provide separate information on any processing beyond this, in particular for marketing purposes, elsewhere in this privacy policy.",
        "We inform contractual partners which data is required in each individual case as part of the data collection process, for example through appropriate labeling in online forms or in personal contact.",
        "Data is deleted as soon as it is no longer required for the aforementioned purposes and no statutory retention obligations preclude deletion. Statutory retention periods, in particular under commercial and tax law, may require longer storage. Data transmitted to us in connection with a specific order is deleted by us after completion of the order and expiry of any applicable retention periods, provided no further statutory or contractual obligations to store the data exist.",
        "The legal basis for the processing is Art. 6(1)(b) GDPR for carrying out pre-contractual measures and for performing the respective contractual relationship, as well as Art. 6(1)(c) GDPR for fulfilling statutory obligations. Insofar as the processing is based on legitimate interests, it is carried out on the basis of Art. 6(1)(f) GDPR. Insofar as the processing is based on Art. 6(1)(f) GDPR, it is carried out to safeguard our legitimate interests in proper and efficient business organization, the internal administration and documentation of business transactions, the assertion and defense of legal claims, ensuring IT and data security, preventing misuse and fraud, and the economic management and further development of our business operations.",
        "- Types of data processed: Inventory data (e.g. full name, home address, contact information, customer number, etc.); payment data (e.g. bank details, invoices, payment history); contact data (e.g. postal and email addresses or telephone numbers). Contract data (e.g. subject matter of the contract, duration, customer category).",
        "- Data subjects: Service recipients and clients; prospective customers; business and contractual partners. Trainees and course participants.",
        "- Purposes of processing and legitimate interests: Provision of contractual services and fulfillment of contractual obligations; communication; office and organizational procedures; organizational and administrative procedures. Business processes and business management procedures.",
        '- Retention and deletion: Deletion in accordance with the information provided in the section "General Information on Data Storage and Deletion".',
        "- Legal bases: Performance of a contract and pre-contractual inquiries (Art. 6(1) sentence 1(b) GDPR); legal obligation (Art. 6(1) sentence 1(c) GDPR). Legitimate interests (Art. 6(1) sentence 1(f) GDPR).",
        "Further information on processing activities, procedures, and services:",
        "- Educational and training services: We process the data of participants in our educational and training programs (collectively referred to as \"trainees\") in order to be able to provide our training services to them. The data processed in this context, and the nature, scope, purpose, and necessity of its processing, are determined by the underlying contractual and training relationship. Forms of processing also include performance assessment and the evaluation of our services and those of the instructors. In the course of our activities, we may also process special categories of data, in particular information on the health of trainees, as well as data revealing racial or ethnic origin, political opinions, or religious or philosophical beliefs. Where necessary, we obtain the trainees' explicit consent for this purpose, and otherwise process special categories of data only where this is necessary to provide the training services, for purposes of preventive health care, social protection, or the protection of the trainees' vital interests; legal bases: performance of a contract and pre-contractual inquiries (Art. 6(1) sentence 1(b) GDPR).",
      ],
    },
    {
      heading: "Provision of the Online Offer and Web Hosting",
      body: [
        "We process users' data in order to be able to provide our online services to them. For this purpose, we process the user's IP address, which is necessary to deliver the content and functions of our online services to the user's browser or device.",
        "- Types of data processed: Usage data (e.g. page views and time spent, click paths, usage intensity and frequency, device types and operating systems used, interactions with content and functions); meta, communication and procedural data (e.g. IP addresses, timestamps, identification numbers, persons involved). Log data (e.g. log files relating to logins or the retrieval of data, or access times).",
        "- Data subjects: Users (e.g. website visitors, users of online services).",
        "- Purposes of processing and legitimate interests: Provision of our online offer and user-friendliness; information technology infrastructure (operation and provision of information systems and technical equipment (computers, servers, etc.)). Security measures.",
        '- Retention and deletion: Deletion in accordance with the information provided in the section "General Information on Data Storage and Deletion".',
        "- Legal bases: Legitimate interests (Art. 6(1) sentence 1(f) GDPR).",
        "Further information on processing activities, procedures, and services:",
        '- Provision of the online offer on rented storage space: To provide our online offer, we use storage space, computing capacity, and software that we rent or otherwise obtain from a corresponding server provider (also referred to as a "web host"); legal bases: legitimate interests (Art. 6(1) sentence 1(f) GDPR).',
        '- Collection of access data and log files: Access to our online offer is logged in the form of so-called "server log files". Server log files may include the address and name of the web pages and files accessed, the date and time of access, the amount of data transferred, a message indicating successful retrieval, the browser type and version, the user\'s operating system, the referrer URL (the previously visited page), and, as a rule, IP addresses and the requesting provider. Server log files may be used, on the one hand, for security purposes, e.g. to avoid overloading the servers (in particular in the event of abusive attacks, so-called DDoS attacks), and, on the other hand, to ensure server load and stability; legal bases: legitimate interests (Art. 6(1) sentence 1(f) GDPR). Deletion of data: Log file information is stored for a maximum of 30 days and is then deleted or anonymized. Data whose continued retention is required for evidentiary purposes is exempt from deletion until the respective incident has been finally resolved.',
        '- Content delivery network: We use a "content delivery network" (CDN). A CDN is a service by means of which the content of an online offer, in particular large media files such as graphics or program scripts, can be delivered more quickly and securely with the help of regionally distributed servers connected via the internet; legal bases: legitimate interests (Art. 6(1) sentence 1(f) GDPR).',
      ],
    },
    {
      heading: "Contact and Inquiry Management",
      body: [
        "When you contact us (e.g. by post, contact form, email, telephone, or via social media), as well as within the context of existing user and business relationships, the information provided by the persons making the inquiry is processed to the extent necessary to respond to the contact inquiries and any requested measures.",
        "- Types of data processed: Contact data (e.g. postal and email addresses or telephone numbers); content data (e.g. text or image messages and posts, as well as related information such as authorship details or the time of creation). Meta, communication and procedural data (e.g. IP addresses, timestamps, identification numbers, persons involved).",
        "- Data subjects: Communication partners.",
        "- Purposes of processing and legitimate interests: Communication; organizational and administrative procedures; feedback (e.g. collecting feedback via an online form). Provision of our online offer and user-friendliness.",
        '- Retention and deletion: Deletion in accordance with the information provided in the section "General Information on Data Storage and Deletion".',
        "- Legal bases: Legitimate interests (Art. 6(1) sentence 1(f) GDPR). Performance of a contract and pre-contractual inquiries (Art. 6(1) sentence 1(b) GDPR).",
        "Further information on processing activities, procedures, and services:",
        "- Contact form: When you contact us via our contact form, by email, or through other means of communication, we process the personal data transmitted to us in order to respond to and handle the respective inquiry. This generally includes information such as name, contact details, and, where applicable, further information communicated to us that is necessary for appropriate handling. We use this data exclusively for the stated purpose of establishing contact and communication; legal bases: performance of a contract and pre-contractual inquiries (Art. 6(1) sentence 1(b) GDPR), legitimate interests (Art. 6(1) sentence 1(f) GDPR).",
      ],
    },
    {
      heading: "Amendment and Update",
      body: [
        "We ask that you regularly inform yourself about the content of our privacy policy. We will amend the privacy policy as soon as changes to the data processing activities we carry out make this necessary. We will inform you as soon as the changes require an act of participation on your part (e.g. consent) or any other individual notification.",
        "Insofar as we provide addresses and contact information for companies and organizations in this privacy policy, please note that such addresses may change over time, and we ask that you verify the details before making contact.",
      ],
    },
    {
      heading: "Definitions",
      body: [
        "In this section, you will find an overview of the terms used in this privacy policy. Insofar as the terms are defined by law, their statutory definitions apply. The following explanations, by contrast, are intended primarily to aid understanding.",
        "- Employees: Employees are persons who are in an employment relationship, whether as staff, salaried employees, or in similar positions. An employment relationship is a legal relationship between an employer and an employee, established by an employment contract or agreement. It includes the employer's obligation to pay the employee remuneration while the employee performs their work. The employment relationship comprises various phases, including its establishment, in which the employment contract is concluded; its performance, during which the employee carries out their work; and its termination, when the employment relationship ends, whether through dismissal, a termination agreement, or otherwise. Employee data is all information relating to these persons that arises in the context of their employment. This includes aspects such as personal identification data, identification numbers, salary and bank details, working hours, vacation entitlements, health data, and performance evaluations.",
        "- Inventory data: Inventory data comprises essential information necessary for identifying and managing contractual partners, user accounts, profiles, and similar assignments. This data may include, among other things, personal and demographic information such as names, contact information (addresses, telephone numbers, email addresses), dates of birth, and specific identifiers (user IDs). Inventory data forms the basis for any formal interaction between persons and services, facilities, or systems, by enabling unambiguous assignment and communication.",
        "- Content data: Content data comprises information generated in the course of creating, editing, and publishing content of any kind. This category of data may include text, images, videos, audio files, and other multimedia content published on various platforms and media. Content data is not limited to the actual content itself, but also includes metadata that provides information about the content, such as tags, descriptions, author information, and publication dates.",
        "- Contact data: Contact data is essential information that enables communication with persons or organizations. It includes, among other things, telephone numbers, postal addresses, and email addresses, as well as means of communication such as social media handles and instant messaging identifiers.",
        "- Meta, communication and procedural data: Meta, communication, and procedural data are categories that contain information about the manner in which data is processed, transmitted, and managed. Metadata, also known as data about data, comprises information describing the context, origin, and structure of other data. It may include details on file size, creation date, the author of a document, and change histories. Communication data records the exchange of information between users across various channels, such as email traffic, call logs, social network messages, and chat histories, including the persons involved, timestamps, and transmission routes. Procedural data describes the processes and workflows within systems or organizations, including workflow documentation, transaction and activity logs, and audit logs used to track and review operations.",
        "- Usage data: Usage data refers to information that records how users interact with digital products, services, or platforms. This data encompasses a wide range of information showing how users use applications, which functions they prefer, how long they spend on particular pages, and the paths they take through an application. Usage data may also include the frequency of use, timestamps of activities, IP addresses, device information, and location data. It is particularly valuable for analyzing user behavior, optimizing user experiences, personalizing content, and improving products or services. In addition, usage data plays a crucial role in identifying trends, preferences, and potential problem areas within digital offerings.",
        '- Personal data: "Personal data" means any information relating to an identified or identifiable natural person (hereinafter "data subject"); an identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier (e.g. a cookie), or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural, or social identity of that natural person.',
        "- Log data: Log data is information about events or activities that have been logged in a system or network. This data typically contains information such as timestamps, IP addresses, user actions, error messages, and other details about the use or operation of a system. Log data is often used to analyze system issues, for security monitoring, or to generate performance reports.",
        '- Controller: The "controller" is the natural or legal person, public authority, agency, or other body which, alone or jointly with others, determines the purposes and means of the processing of personal data.',
        '- Processing: "Processing" means any operation or set of operations performed on personal data, whether or not by automated means. The term is broad and covers virtually any handling of data, whether it be collecting, evaluating, storing, transmitting, or deleting it.',
        "- Contract data: Contract data is specific information relating to the formalization of an agreement between two or more parties. It documents the conditions under which services or products are provided, exchanged, or sold. This category of data is essential for managing and fulfilling contractual obligations and includes both the identification of the contracting parties and the specific terms and conditions of the agreement. Contract data may include the start and end dates of the contract, the type of services or products agreed upon, pricing arrangements, payment terms, termination rights, renewal options, and special conditions or clauses. It serves as the legal basis for the relationship between the parties and is crucial for clarifying rights and obligations, enforcing claims, and resolving disputes.",
        "- Payment data: Payment data comprises all information required to process payment transactions between buyers and sellers. This data is of critical importance for e-commerce, online banking, and any other form of financial transaction. It includes details such as credit card numbers, bank details, payment amounts, transaction data, verification numbers, and invoice information. Payment data may also include information on payment status, chargebacks, authorizations, and fees.",
        "Created with the free privacy policy generator at Datenschutz-Generator.de by Dr. Thomas Schwenke",
      ],
    },
  ],
};
